### PR TITLE
Update and fix Pubmed crawler

### PR DESCRIPTION
**Pull request by vpchung**
Not sure what happened, but `alive_progress` is no longer compatible with Docker:

```
...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 2111, in shutdown
    h.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
  File "/usr/local/lib/python3.8/site-packages/alive_progress/core/hook_manager.py", line 33, in flush
    if buffers[stream]:
TypeError: unhashable type: 'types.SimpleNamespace'
```

It continues to work as expected when running the script directly though.....  Regardless, I decided to remove the live progress bar altogether, since it's not really needed for the overall workflow.  Running the Docker container with the latest changes should now work smoothly again:

```
Downloading  [####################]100.00%   195.8kB/195.8kB (776.3kB/s) SYNAPSE_TABLE_QUERY_95104362.csv Done...
    Querying for grant numbers... 77 found

Getting PMIDs from NCBI...
  Total unique publications: 2524

Comparing with table syn21868591...
Downloading  [####################]100.00%   2.2MB/2.2MB (4.1MB/s) SYNAPSE_TABLE_QUERY_95104393.csv Done...
      New publications found: 76

Pulling information from publications... DONE ✓
Downloading  [####################]100.00%   43.0kB/43.0kB (566.8kB/s) SYNAPSE_TABLE_QUERY_95104399.csv Done...
```

Other notable update in the PR include:
* removing data validation rules from the files manifest
* updating the Synapse login to use PAT instead of username/API key

### CODE REVIEW

**Comment by vpchung** [comment]
@brynnz22 can you let me know if the latest pubmed_crawler works on your end?

```
$ docker pull docker.synapse.org/syn7080714/pubmed_crawler
$ docker run --rm -ti \
  --env-file /path/to/.env \
  --volume $PWD/output:/output:rw \
  docker.synapse.org/syn7080714/pubmed_crawler
```

**Comment by brynnz22** [comment]
@Verena this did not work:

**Comment by brynnz22** [comment]
@vpchung it did not work: 

```
Brynns-MBP:python bzalmanek$ docker run --rm -ti \
>   --env-file .env  \
>   --volume $PWD/output:/output:rw \
>   docker.synapse.org/syn7080714/pubmed_crawler

 [####################]100.00%   1/1   Done...
Downloading  [####################]100.00%   195.8kB/195.8kB (850.3kB/s) SYNAPSE_TABLE_QUERY_95142177.csv Done...
    Querying for grant numbers...77 found

Getting PMIDs from NCBI...
  01. Grant number CA202177...69 found
  02. Grant number CA209992...100 found
  03. Grant number CA243073...4 found
  04. Grant number CA202123...49 found
  05. Grant number CA238720...7 found
  06. Grant number CA209978...74 found
  07. Grant number CA209923...6 found
  08. Grant number CA209988...57 found
  09. Grant number CA199315...19 found
  10. Grant number CA215798...21 found
  11. Grant number CA214381...27 found
  12. Grant number CA244100...8 found
  13. Grant number CA240301...10 found
  14. Grant number CA217377...47 found
  15. Grant number CA193419...117 found
  16. Grant number CA214369...14 found
  17. Grant number CA202229...21 found
  18. Grant number CA214411...38 found
  19. Grant number CA214292...19 found
  20. Grant number CA210173...88 found
  21. Grant number CA217297...65 found
  22. Grant number CA217378...40 found
  23. Grant number CA209975...31 found
  24. Grant number CA184898...24 found
  25. Grant number CA244109...12 found
  26. Grant number CA209997...77 found
  27. Grant number CA244107...2 found
  28. Grant number CA232209...17 found
  29. Grant number CA231978...4 found
  30. Grant number CA215845...23 found
  31. Grant number CA244101...5 found
  32. Grant number CA232137...10 found
  33. Grant number CA250046...4 found
  34. Grant number CA214300...29 found
  35. Grant number CA232382...15 found
  36. Grant number CA250040...4 found
  37. Grant number CA209971...34 found
  38. Grant number CA227550...24 found
  39. Grant number CA215794...12 found
  40. Grant number CA241927...0 found
  41. Grant number CA232161...3 found
  42. Grant number CA195469...13 found
  43. Grant number CA225088...116 found
  44. Grant number CA232216...7 found
  45. Grant number CA232517...12 found
  46. Grant number CA238728...2 found
  47. Grant number CA193461...81 found
  48. Grant number CA227136...38 found
  49. Grant number CA202241...51 found
  50. Grant number CA217655...12 found
  51. Grant number CA214282...3 found
  52. Grant number CA243072...15 found
  53. Grant number CA210190...54 found
  54. Grant number CA210181...137 found
  55. Grant number CA217450...57 found
  56. Grant number CA193489...108 found
  57. Grant number CA214354...21 found
  58. Grant number CA238475...6 found
  59. Grant number CA245313...6 found
  60. Grant number CA184897...9 found
  61. Grant number CA215709...6 found
  62. Grant number CA210152...50 found
  63. Grant number CA210180...68 found
  64. Grant number CA209891...92 found
  65. Grant number CA243007...0 found
  66. Grant number CA210184...147 found
  67. Grant number CA188388...22 found
  68. Grant number CA243075...6 found
  69. Grant number CA215848...13 found
  70. Grant number CA193313...81 found
  71. Grant number CA202144...4 found
  72. Grant number CA193417...132 found
  73. Grant number CA227544...4 found
  74. Grant number CA225566...5 found
  75. Grant number CA214297...10 found
  76. Grant number CA217376...73 found
  77. Grant number CA220378...45 found
Total unique publications: 2524

Comparing with table syn21868591...
 [####################]100.00%   1/1   Done...
Downloading  [##################--]90.76%   2.0MB/2.2MB (3.5MB/s) SYNAPSE_TDownloading  [####################]100.00%   2.2MB/2.2MB (3.8MB/s) SYNAPSE_TABLE_QUERY_95142229.csv Done...
      New publications found: 76

Pulling information from publications...
Traceback (most recent call last):
  File "pubmed_crawler.py", line 424, in <module>
    main()
  File "pubmed_crawler.py", line 419, in main
    table = find_publications(syn, args.grantview_id, args.table_id)
  File "pubmed_crawler.py", line 373, in find_publications
    table = scrape_info(pmids, grants, grant_view)
  File "pubmed_crawler.py", line 249, in scrape_info
    with alive_bar(len(pmids)) as progress:
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/alive_progress/core/progress.py", line 276, in __alive_bar
    start_monitoring()
  File "/usr/local/lib/python3.7/site-packages/alive_progress/core/progress.py", line 163, in start_monitoring
    hook_manager.install()
  File "/usr/local/lib/python3.7/site-packages/alive_progress/core/hook_manager.py", line 76, in install
    for logger in get_all_loggers()
  File "/usr/local/lib/python3.7/site-packages/alive_progress/core/hook_manager.py", line 77, in <dictcomp>
    for h in logger.handlers if isinstance(h, StreamHandler)})
  File "/usr/local/lib/python3.7/site-packages/alive_progress/core/hook_manager.py", line 64, in get_hook_for
    handler.stream.flush()
  File "/usr/local/lib/python3.7/site-packages/alive_progress/core/hook_manager.py", line 33, in flush
    if buffers[stream]:
TypeError: unhashable type: 'types.SimpleNamespace'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 2033, in shutdown
    h.flush()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
  File "/usr/local/lib/python3.7/site-packages/alive_progress/core/hook_manager.py", line 33, in flush
    if buffers[stream]:
TypeError: unhashable type: 'types.SimpleNamespace'
 [####################]100.00%   1/1   Done...
Downloading  [####################]100.00%   43.0kB/43.0kB (524.0kB/s) SYNAPSE_TABLE_QUERY_95142236.csv Done...
    [WARNING] /usr/local/lib/python3.7/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
```

**Comment by vpchung** [comment]
D'oh, it's because I did not push up the changes to the hub.  Sorry - it is [updated now](https://www.synapse.org/#!Synapse:syn26467915)!

**Comment by brynnz22** [comment]
It works!

**Review by brynnz22 — APPROVED** [review]

**Review by brynnz22 — APPROVED** [review]

**Pull request merged**
