### PR TITLE
script for adding new grants to the portal

### PR DESCRIPTION
**Pull request by vpchung**
This script will iterate through a CSV file (see new_grants_template.csv) and create a new Synapse Project and Wiki pages for each listed grant. The **Portals - Grants Merged** table will also be updated to include their metadata.

### CODE REVIEW

**Comment by jaeddy** [comment]
@vpchung I'm going to hold off on this PR for now. Ideally, we'd use this script to update the [`grant`](https://www.synapse.org/#!Synapse:syn21639712/tables/) table in the DB project, not the merged (which should only be updated via the ETL pipeline moving forward). However, we need to work with Andrew's reverse-ETL code first to make sure all the recent manual edits have been correctly back-propagated.

**Comment by vpchung** [comment]
Thanks @jaeddy , that makes a lot of sense!

Side question: would it be better to have all our pipeline scripts in one language? Or is it okay for me to continue working in Python?

**Comment by jaeddy** [comment]
I don't see any problem at the moment with keeping scripts in both R and Python (if we ever decide to make a "package" we can revisit). For now, everyone should use whichever they feel most productive and efficient using!

**Comment by jaeddy** [comment]
Hmm.. I accidentally merged this PR and had to revert, but can't seem to re-open the original. @vpchung can you (re)create a new PR? Sorry about the mixup.

**Comment by vpchung** [comment]
Done! #93

**Pull request merged**
